spring.application.name=botreport

bot.telegram.username=green_state_bonus_bot
bot.telegram.token=8105544952:AAHsM9wp71_368n1TfHTzfENij82alRfHFE

# Google Sheets
google.sheets.spreadsheetId=1bbE_cVZbP8feTltwpY9pz-UfRKrFFetJd12-gJvF8Dc
google.sheets.sheetName=report
google.sheets.shopSheetName=shop
google.sheets.credentialsPath=u420report.json



